In [2]:
import pandas as pd

In [9]:
friend_dict_list = [{'name': 'Jone', 'age': 20, 'job': 'student'},
         {'name': 'Jenny', 'age': 30, 'job': None},
         {'name': 'Nate', 'age': 30, 'job': 'teacher'}]

In [10]:
df = pd.DataFrame(friend_dict_list)

In [11]:
df.head()

    name  age      job
0   Jone   20  student
1  Jenny   30     None
2   Nate   30  teacher

In [12]:
df.to_csv('friends.csv', index= True, header= True, na_rep= '-')